### ISSUE TITLE
Issues when running the baselines

### ISSUE THREAD

**Issue by jmunozmendiFunditec** [dkorenci/pan-clef-2024-oppositional#1]
While running the baselines (`classif_experiment_runner.py`), I encountered the following issues:

- The predict method of the SklearnTransformerClassif throws an error since the method from_list does not exist. It can be fixed by replacing the function with:

```python
def predict(self, X):
    '''
    :param X: list-like of texts
    :return: array of label predictions
    '''
    ...
    df = pd.DataFrame([{'text': txt} for txt in X])
    dset = datasets.Dataset.from_pandas(df)

```

- Another issue occurs in the SklearnTransformerBase class, where the CUDA device is not set properly:

```python
        if device: self._device = device
        else: self._device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
```
should be replaced by:

```python
        if device: self._device = device
        else: self._device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
```

- Now I'm stuck in the score calculation phase, where I am unable to get past the error:

```
Traceback (most recent call last): 
File "/notebooks/pan-clef-2024-oppositional/classif_experim/classif_experiment_runner.py", line 170, in run_all_critic_conspi() 
File "/notebooks/pan-clef-2024-oppositional/classif_experim/classif_experiment_runner.py", line 165, in run_all_critic_conspi run_classif_experiments(lang=lang, num_folds=5, rnd_seed=seed, test=None, 
File "/notebooks/pan-clef-2024-oppositional/classif_experim/classif_experiment_runner.py", line 142, in run_classif_experiments res = run_classif_crossvalid(lang=lang, model_label=model, model_params=params, num_folds=num_folds, 
File "/notebooks/pan-clef-2024-oppositional/classif_experim/classif_experiment_runner.py", line 52, in run_classif_crossvalid scores = pd.DataFrame({fname: [f(cls_tst, cls_pred)] for fname, f in score_fns.items()}) 
File "/notebooks/pan-clef-2024-oppositional/classif_experim/classif_experiment_runner.py", line 52, in scores = pd.DataFrame({fname: [f(cls_tst, cls_pred)] for fname, f in score_fns.items()}) 
File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py", line 1136, in f1_score return fbeta_score( 
File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py", line 1277, in fbeta_score _, _, f, _ = precision_recall_fscore_support( 
File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py", line 1563, in precision_recall_fscore_support labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label) 
File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py", line 1372, in _check_set_wise_labels raise ValueError( ValueError: pos_label=1 is not a valid label. It should be one of ['CONSPIRACY', 'CRITICAL']

```

**Comment by dkorenci** [comment]
The bug that caused the error below is now solved. 

Cuda issue should not matter, 'cuda' should imply 'cuda:0' on a 1-gpu machine, otherwise the desired device should be specified. 

For the predict issue, it seems that your version of the datasets library does not support the method.
I have to check which is the best solution for this.
